export const CREATE_TRIP = "CREATE_TRIP";
export const RETRIEVE_TRIPS = "RETRIEVE_TRIPS";
export const UPDATE_TRIP = "UPDATE_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const DELETE_ALL_TRIPS = "DELETE_ALL_TRIPS";